
configVersion: "1.0"
debug: true
plugin_message_prefix: "&f[&5GroupChat&f] "

chat:
  # Should the message also be displayed in the console ?
  show_msg_console: true

  #Available parameters:
  # {group.prefix} -> prefix that the group uses
  # {group.name} -> prefix that the group uses
  # {user.name} -> name of the user that sent the message
  # {user.displayName} -> display name of the user that sent the message
  chat_prefix: "&f[&5groupchat&f] &f[&c{group.prefix}&f] {user.displayName} : &7"

sql:
  # SQLite, MySQL are supported databases
  driver: SQLite
  # Database server address.
  address: localhost:3306
  # Database name, username and password.
  database: 'groupchat'
  username: ''
  password: ''
  table_prefix: 'groupchat_'

  # ...interval in seconds, when the database should be pinged,
  # to keep the connection alive
  # You can set this to '0' to disable the ping interval
  ping_interval: 3600

  # Database engine. Only applies to MySQL.
  engine: InnoDB

  options: 'useSSL=false&serverTimezone=UTC'

sync:
  server: lobby
  enabled: true
  # Here are all the settings used for REDIS server, if you want a smooth
  # communication of the plugin across BungeeCord servers, this needs to be setup properly.
  # This only works if the sql == MySQL !
  ip: localhost
  port: 6379
  username: ""
  password: ""
  message_channel: "mc_GroupChat" # this value should be the same across server config files



groups:
  - tier: 0
    member_limit: 5
    public: false
    requirements: []
  - tier: 1
    member_limit: 10
    public: false
    requirements:
      - money 50000
      - permission group.emerald
      - item diamond 128
  - tier: 2
    member_limit: 20
    public: false
    requirements:
      - money 30000
      - permission group.vip
      - item diamond 128
  - tier: 3
    member_limit: 20
    public: true
    requirements:
      - money 30000
      - permission group.vip
      - item diamond 128



