name: GroupChat
version: ${project.version}
main: com.pustinek.groupchat.Main
api-version: "1.13"
authors: [Pustinek]
description: "group chat for minecraft servers running Spigot/Paper"
commands:
  groupchat:
    description: 'for all the commands use /groupchat help'
    usage: 'groupchat has not started correctly, check the log file (or console) and correct any errors.'
    aliases: [gchat]
    permissions:
      groupchat.*:
        description: 'Give access to all commands of group chat'
        default: op
        children:
          groupchat.reload: true
          groupchat.status: true
          groupchat.create: true
          groupchat.manage: true
          groupchat.list: true
      groupchat.reload:
        description: 'reload plugin config files'
        default: op
      groupchat.status:
        description: 'Get plugin status'
        default: op
      groupchat.create:
        description: 'Create a group'
        default: op
      groupchat.manage:
        description: 'Manage your group'
        default: op
      groupchat.list:
        description: 'List the groups you own or are the member of'
        default: op